name: Build Windows Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # Add this

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bun
        run: |
          npm install -g bun@1.2.14
          bun --version

      - name: Install dependencies with Bun
        run: bun install
        working-directory: ./ 
        env:
          npm_config_build_from_source: true

      - name: Build app
        run: bun run build
        
      - name: Create executable
        run: bun run dist:win
        
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: MilitaryCouncilSystem-Windows
          path: dist/*.exe
          retention-days: 5