name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install Bun
      run: |
        npm install -g bun@1.2.14
        bun --version
        
    - name: Cache Bun dependencies
      uses: actions/cache@v4
      id: bun-cache
      with:
        path: |
          ~/.bun
          node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
      
    - name: Install dependencies
      run: bun install --frozen-lockfile
      
    - name: Build app
      run: bun run build
      
    - name: Install build tools
      run: |
        npm install --global windows-build-tools
        bun run electron-builder install-app-deps
        
    - name: Create executable
      run: npx electron-builder --win --x64
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyElectronApp
        path: |
          dist/*.exe
          dist/*.blockmap
        retention-days: 5