name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Bun
      run: |
        npm install -g bun@1.2.14
        bun --version

    - name: Install dependencies
      run: bun install  # Remove "--frozen-lockfile"

    - name: Build app
      run: bun run build

    - name: Create executable
      run: npx electron-builder --win --x64 --publish never

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyElectronApp
        path: dist/*.exe
        retention-days: 5
