name: Build Windows Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Add checkout step first
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bun
        run: |
          npm install -g bun@1.2.14
          bun --version

      - name: Install dependencies with Bun
        run: bun install
        working-directory: ./  # Ensure we're in root directory
        env:
          npm_config_build_from_source: true

      - name: Rebuild native modules
        run: |
          bun run electron-rebuild
          bun run electron-builder install-app-deps

      # Add path fixes for Windows
      - name: Fix Windows paths
        run: |
          npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
          git config --global core.autocrlf false

      - name: Build main process
        run: bun run build:main

      - name: Build renderer
        run: bun run build:renderer
      
      - name: Copy database files
        run: bun run copy-db
        
      - name: Create executable
        run: bun run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: MilitaryCouncilSystem-Windows
          path: dist/*.exe
          retention-days: 5