# .github/workflows/windows-build.yml
name: Build Windows Executable

on:
  push:
    branches: [main]  # or whichever branch you use

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Bun (optional, for non-native tasks)
        run: |
          npm install -g bun@1.2.14
          bun --version

      - name: Install JS dependencies
        # Use npm to ensure native modules can rebuild
        run: npm ci

      - name: Rebuild native modules
        run: |
          # Ensure better-sqlite3 and friends compile against Electron
          npm rebuild better-sqlite3 --build-from-source
          npm rebuild better-sqlite3-with-prebuilds --build-from-source

      - name: Install Electron app deps
        run: npx electron-builder install-app-deps

      - name: Build main process
        run: npm run build:main

      - name: Build renderer
        run: npm run build:renderer

      - name: Package with Bun (optional)
        run: bun run dist:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create executable (electron-builder)
        run: npx electron-builder --win --x64 --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: MyElectronApp-Windows
          path: dist/*.exe
          retention-days: 5
